- src/app/bounties/page.js
- src/app/home/Main.js
- src/app/layout.js
- src/app/learn/StartOnOpenBuild.js
- src/app/learn/[type]/page.js
- src/app/quiz/page.js
修复了 SartOnOpenBuild 函数名中的拼写错误，将其更正为 StartOnOpenBuild。
此修改仅涉及函数名的拼写修正，不会影响程序的功能逻辑。
已经检查了所有调用 SartOnOpenBuild 的地方，确保它们一致地引用了新的函数名 StartOnOpenBuild。
> fix: correct spelling error in SartOnOpenBuild function

- package.json
- src/app/bounties/[id]/AppliedModal.js
- src/app/bounties/[id]/ApplyFinishedModal.js
- src/app/bounties/[id]/ApplyModal.js
- src/app/bounties/[id]/TerminateModal.js
- src/app/creator/build/[type]/AppliedModal.js
- src/app/creator/build/[type]/BountyList.js
- src/app/creator/build/[type]/ManageModal.js
- src/app/creator/learn/[type]/[id]/StepThree.js
- src/app/creator/learn/[type]/page.js
- src/app/dashboard/build/ManageModal.js
- src/app/dashboard/hire/TerminateModal.js
- src/app/home/Contributor.js
- src/app/home/Newest.js
- src/app/learn/[type]/CourseCard.js
- src/app/learn/[type]/[id]/RightCard.js
- src/app/learn/[type]/[id]/[chapter_id]/Content.js
- src/app/shilling/HireOnChainModal.js
- src/app/shilling/[id]/Author.js
This pull request addresses several spelling mistakes and improves variable naming conventions across the codebase to enhance readability and maintainability.
- Corrected spelling errors.
- Renamed variables to follow consistent naming conventions.
- Verified that all unit tests pass successfully.
- Manually tested key functionalities to ensure no regressions.
- No functional changes were made; this PR is purely for code quality improvement.
> fix: correct spelling errors and improve variable naming for clarity

- src/shared/components/Filter/index.js
> fix: improve Filter

- src/app/home/BuilderWay.js
> fix(home): fix CardVerticalSlider Hydration failed

- src/app/home/BuilderWay.js
> fix(home): 解决a标签嵌套问题

- README.md
1. 在 README 中添加 quick start 部分
> chore: add quick start

- src/app/learn/Chapters.js
- src/app/learn/[type]/[id]/EmailModal.js
> fix: 修改课程详情页样式

- src/app/shilling/Card.js
> fix(SkillHub): resolve routing issue caused by nested <a> tags

- src/domain/challenge/views/published-challenge-list/PublishedChallengeItem.js
- src/domain/course/index.js
- src/domain/course/views/published-course-list/PublishedCourseItem.js
- src/domain/course/widgets/builder-list/BuilderList.js
- src/domain/course/widgets/builder-list/index.js
- src/domain/profile/widgets/social-info/PublishedCountList.js
- src/domain/skill/views/skill-overview/SkillCircle.js
- src/domain/skill/views/skill-overview/SkillOverview.js
- src/entry/components/Header/Account.js
- src/entry/components/Header/Navs.js
- src/entry/components/Header/index.js
修复 #59 中前 3 个，其中第 3 个因为要**考虑移动端下拉菜单弹出触发问题，将跳转到个人页面的触发点设置到了用户名称上**（移动端这部分隐藏不可见）。
另外，修正项目方个人页面中课程计数的文本拼写。
> Optimize something in profile page

- src/app/bounties/[id]/Employers.js
> Bounty Apply 时如果没有登录则跳转到登录页面

- README.md
- package.json
> chore: optimize startup process

- src/app/learn/[type]/TopFilters.js
- src/app/learn/[type]/page.js
- src/entry/layouts/default/DefaultLayout.js
> 课程列表页移动端适配

- src/app/learn/[type]/TopFilters.js
> fix: 修改课程语言搜索

- src/shared/components/Share/index.js
修改邀请记录 Modal 无法关闭的问题
在 https://openbuild.xyz/learn/challenges/2054935307 点击 Share，再点击 Invitation record，这个 Modal 无法关闭。
> 修改邀请记录 Modal 无法关闭的问题

- src/app/learn/[type]/[id]/[chapter_id]/page.js
- src/app/learn/[type]/[id]/page.js
Description:
This PR resolves the issue where the card displays the default image and title when sharing course or activity chapters. The fix ensures that the card now correctly displays the course image and chapter title.
Changes:
Updated the logic to fetch and display the correct course image and chapter title.
Related Issue: 
https://github.com/openbuildxyz/openbuild-frontend/issues/107
> Fix card display issue when sharing course or activity chapters 

- src/shared/components/control/block-editor/DragHandle.tsx
fixed https://github.com/openbuildxyz/openbuild-frontend/issues/167
> fix: dragHandle menu

- package.json
- src/app/creator/build/[type]/AppliedModal.tsx
- src/app/creator/build/[type]/ManageModal.js
- src/domain/bounty/widgets/process-list/AppliedModal.tsx
- src/domain/reputation/helper/nftAbi.ts
- src/domain/reputation/repository.ts
- src/entry/pages/course-detail/EmailModal.tsx
- src/entry/pages/course-detail/RightCard.tsx
- src/services/creator/hooks.ts
- src/shared/components/Button/index.tsx
- src/shared/components/Modal/index.tsx
- src/shared/constants/abis/bounty.ts
- src/shared/constants/abis/erc20ABI.ts
- src/shared/constants/bounty.ts
- src/shared/utils/abiContractFactory.ts
fixed https://github.com/openbuildxyz/openbuild-frontend/issues/102
通过 abi 生成读和写的函数
重构了这三个 abi 的调用方式
`src/shared/constants/abis/bounty.ts`
`src/domain/reputation/helper/nftAbi.ts`
`src/shared/constants/abis/erc20ABI.ts`
> feat: abiContractFactory

- src/domain/quiz/widgets/quiz-limiter/QuizLimiter.js
> feat(app/quiz): go to related challenge

- src/domain/quiz/views/quiz-detail/QuizDetail.js
- src/domain/quiz/widgets/quiz-limiter/QuizLimiter.js
修改 #206 
之前点击 Challenge now 按钮，只提示一次原因，再点击的时候不再提示了。
修复了这个问题。
> fix: update QuizLimiter dependencies

- src/shared/constants/chain.js
> feat(constants/chain): add BSC mainnet chain definition
